# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: ORDA
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#
nav:
   - Главная: index.md
   - О проекте: about.md
    - WebSecurity: WebSecurity.md