site_name: ORDA
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#
nav:
  - Home: 'index.md'
  - 'User Guide'
  - About:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - WebSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'