site_name: ORDA
theme:
  language: ru
  name: material
  
  palette:
    scheme: default
    primary: white
    accent: light blue
    toggle:
      icon: material/brightness-7 
    features:
      - search.highlight
      - search.share
      - header.autohide
      - announce.dismiss
      - navigation.footer
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - content.footnote.tooltips
      - navigation.icons
      - navigation.tabs
      - navigation.instant
      - navigation.sections
      - navigation.top
      - navigation.indexes
  icons:
     - fontawesome: true

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html

nav:
  - Home: 'index.md'
  - About:
    - 'О нас': 'about.md'
  - Безопасность веб приложений: 
    - 'Server-Side уязвимости': 'Backend.md'
    - 'Client-Side уязвимости': 'Frontend.md'
    - 'ApiSecurity': 'ApiSec.md'
  - DevSecOps: 'DevSecOps.md'
  - Книги/Курсы:
    - 'Книги': 'Books.md'
    - 'Курсы': 'Courses.md'
  - Burp Suite Advanced:
    - 'Расширения': 'BurpExtensions.md'
    - 'Tricks': 'BurpTricks.md'
  - Безопасность мобильных приложений: 'mobile.md'
  - Контейнерная безопасность: 'container.md'
  - Облачная безопасность: 'cloud.md'
  - Безопасность CI/CD: 'cicdsecurity.md'
  - Уязвимые приложения:
    - 'Онлайн приложения': 'Online_Apps.md'
    - 'Оффлайн приложения': 'Offline_Apps.md'
  - Постановления регуляторов:
    - 'Сводка': 'regulators.md'
  - Contributors: 'contributors.md'
  - Blog:
    - blog/index.md
extra:
  consent:
    title: Куки кику
    description: >- 
      Мы используем твои печеньки .. Впрочем, ты и так всё понимаешь.
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/
      name: telegram сообщество для ORDA
  generator: false

plugins:
  - privacy:
      cache: false
  - blog:
      post_date_format: medium
      archive_date_format: yyyy
      
      categories: true
      categories_name: DevSecOps

      post_dir: "{blog}/posts"
  - search:
      lang: 
        - ru
        - en

extra_javascript:
  - javascripts/consent.js

copyright: Copyright &copy; 2024 ORDA