site_name: ORDA
theme:
  language: ru
  name: material
  palette:
    scheme: default
    primary: white
    accent: light blue
    toggle:
      icon: material/brightness-7 
    features:
      - search.highlight
      - search.share
      - header.autohide
      - announce.dismiss
      - navigation.footer

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#

nav:
  - Home: 'index.md'
  - About:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - WebSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'

extra:
  consent:
    title: Куки кику
    description: >- 
      Мы используем твои печеньки .. Впрочем, ты и так всё понимаешь.
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/