site_name: ORDA
theme:
  language: ru
  name: material
  palette:
    scheme: default
    primary: white
    accent: light blue
    toggle:
      icon: material/brightness-7 
    features:
      - search.highlight
      - search.share
      - header.autohide
      - announce.dismiss
      - navigation.footer
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - content.footnote.tooltips

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - go
    - js
    - c++
    - C#

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

nav:
  - Home: 'index.md'
  - About:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - WebSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'
  - ApiSecurity:
    - 'О нас': 'about.md'
    - 'Ещё о нас': 'about.md'

extra:
  consent:
    title: Куки кику
    description: >- 
      Мы используем твои печеньки .. Впрочем, ты и так всё понимаешь.
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/